# config for run REST server on your local JVM
database:
  driverClass: com.mysql.jdbc.Driver
  url: 'jdbc:mysql://localhost/sample'
  user: root
  password: root
logging:
  level: WARN
  loggers:
    com.example.sample: DEBUG
  appenders:
    - type: console
